[package]
name = "pef"
version = "0.1.1"
edition = "2021"
description = "Partitioned Elias Fano Variation."
repository = "https://github.com/github/rust-gems"
license = "MIT"
keywords = ["tokenizer", "algorithm", "encoding", "bpe"]
categories = ["algorithms", "data-structures", "encoding", "science"]

[lib]
crate-type = ["lib", "staticlib"]
bench = false

[dependencies]
itertools = "0.14"
rand = { version = "0.9", optional = true }
